export const staticData = [
  {
    "Provider ID": "090001",
    "Hospital Name": "GEORGE WASHINGTON UNIV HOSPITAL",
    Address: "900 23RD ST NW",
    City: "WASHINGTON",
    State: "DC",
    "ZIP Code": 20037,
    "County Name": "DISTRICT OF COLUMBIA",
    "Phone Number": 2027164605,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Proprietary",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 1,
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Below the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Below the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Below the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Same as the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Below the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison":
      "Same as the national average",
    "Efficient use of medical imaging national comparison footnote": "",
  },
  {
    "Provider ID": "090003",
    "Hospital Name": "HOWARD UNIVERSITY HOSPITAL",
    Address: "2041 GEORGIA AVE NW",
    City: "WASHINGTON",
    State: "DC",
    "ZIP Code": 20060,
    "County Name": "DISTRICT OF COLUMBIA",
    "Phone Number": 2027456100,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Voluntary non-profit - Other",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 1,
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Below the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Below the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Below the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Same as the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Below the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison":
      "Same as the national average",
    "Efficient use of medical imaging national comparison footnote": "",
  },
  {
    "Provider ID": "090004",
    "Hospital Name": "MEDSTAR GEORGETOWN UNIVERSITY HOSPITAL",
    Address: "3800 RESERVOIR RD",
    City: "WASHINGTON",
    State: "DC",
    "ZIP Code": 20007,
    "County Name": "DISTRICT OF COLUMBIA",
    "Phone Number": 2027843000,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Voluntary non-profit - Private",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 1,
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Below the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Below the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Below the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Same as the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Below the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison":
      "Above the national average",
    "Efficient use of medical imaging national comparison footnote": "",
  },
  {
    "Provider ID": "090005",
    "Hospital Name": "SIBLEY MEMORIAL HOSPITAL",
    Address: "5255 LOUGHBORO RD NW",
    City: "WASHINGTON",
    State: "DC",
    "ZIP Code": 20016,
    "County Name": "DISTRICT OF COLUMBIA",
    "Phone Number": 2025374680,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Voluntary non-profit - Other",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 3,
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Below the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Above the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Below the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Same as the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Below the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison":
      "Above the national average",
    "Efficient use of medical imaging national comparison footnote": "",
  },
  {
    "Provider ID": "090006",
    "Hospital Name": "PROVIDENCE HOSPITAL",
    Address: "1150 VARNUM ST NE",
    City: "WASHINGTON",
    State: "DC",
    "ZIP Code": 20017,
    "County Name": "DISTRICT OF COLUMBIA",
    "Phone Number": 2022697000,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Voluntary non-profit - Private",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 1,
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Above the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Below the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Below the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Below the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Below the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Below the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison":
      "Same as the national average",
    "Efficient use of medical imaging national comparison footnote": "",
  },
  {
    "Provider ID": "090008",
    "Hospital Name": "UNITED MEDICAL CENTER",
    Address: "1310 SOUTHERN AVENUE  SE",
    City: "WASHINGTON",
    State: "DC",
    "ZIP Code": 20032,
    "County Name": "DISTRICT OF COLUMBIA",
    "Phone Number": 2025746611,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Proprietary",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 1,
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Same as the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Above the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Below the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Below the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Below the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Below the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison":
      "Same as the national average",
    "Efficient use of medical imaging national comparison footnote": "",
  },
  {
    "Provider ID": "090011",
    "Hospital Name": "MEDSTAR WASHINGTON HOSPITAL CENTER",
    Address: "110 IRVING ST NW",
    City: "WASHINGTON",
    State: "DC",
    "ZIP Code": 20010,
    "County Name": "DISTRICT OF COLUMBIA",
    "Phone Number": 2028777000,
    "Hospital Type": "Acute Care Hospitals",
    "Hospital Ownership": "Voluntary non-profit - Other",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": 2,
    "Hospital overall rating footnote": "",
    "Mortality national comparison": "Above the national average",
    "Mortality national comparison footnote": "",
    "Safety of care national comparison": "Below the national average",
    "Safety of care national comparison footnote": "",
    "Readmission national comparison": "Below the national average",
    "Readmission national comparison footnote": "",
    "Patient experience national comparison": "Below the national average",
    "Patient experience national comparison footnote": "",
    "Effectiveness of care national comparison": "Below the national average",
    "Effectiveness of care national comparison footnote": "",
    "Timeliness of care national comparison": "Below the national average",
    "Timeliness of care national comparison footnote": "",
    "Efficient use of medical imaging national comparison":
      "Above the national average",
    "Efficient use of medical imaging national comparison footnote": "",
  },
  {
    "Provider ID": "093300",
    "Hospital Name": "CHILDREN'S HOSPITAL NMC",
    Address: "111 MICHIGAN AVE, NW",
    City: "WASHINGTON",
    State: "DC",
    "ZIP Code": 20010,
    "County Name": "DISTRICT OF COLUMBIA",
    "Phone Number": 2024765000,
    "Hospital Type": "Childrens",
    "Hospital Ownership": "Voluntary non-profit - Private",
    "Emergency Services": "Yes",
    "Meets criteria for meaningful use of EHRs": "Y",
    "Hospital overall rating": "Not Available",
    "Hospital overall rating footnote":
      "Results are not available for this reporting period",
    "Mortality national comparison": "Not Available",
    "Mortality national comparison footnote":
      "Results are not available for this reporting period",
    "Safety of care national comparison": "Not Available",
    "Safety of care national comparison footnote":
      "Results are not available for this reporting period",
    "Readmission national comparison": "Not Available",
    "Readmission national comparison footnote":
      "Results are not available for this reporting period",
    "Patient experience national comparison": "Not Available",
    "Patient experience national comparison footnote":
      "Results are not available for this reporting period",
    "Effectiveness of care national comparison": "Not Available",
    "Effectiveness of care national comparison footnote":
      "Results are not available for this reporting period",
    "Timeliness of care national comparison": "Not Available",
    "Timeliness of care national comparison footnote":
      "Results are not available for this reporting period",
    "Efficient use of medical imaging national comparison": "Not Available",
    "Efficient use of medical imaging national comparison footnote":
      "Results are not available for this reporting period",
  },
];
